config/routes.rb
Rails.application.routes.draw do
  root 'universes#index'

  get '/:name', to: 'universes#show', as: :universe_detail

  get '/:name/locations', to: 'locations#index', as: :locations_index
  get '/locations/drill/:id', to: 'locations#drill', as: :location_drill
  get '/locations/climb/:id', to: 'locations#drill', as: :location_climb
  get '/:name/locations/:location', to: 'locations#show', as: :location_show
  post '/:name/locations/search', to: 'locations#search', as: :location_search
  get '/:universe/locations/:location/description', to: 'locations#description', as: :location_description
  post '/:universe/locations/:location/description', to: 'locations#update_description', as: :location_update_description
  post '/locations/create', to: 'locations#create', as: :location_create

  get '/:name/people', to: 'people#index', as: :people_index
  get '/:name/description', to: 'universes#description', as: :universe_description
  post '/:name/description', to: 'universes#update_description', as: :universe_update_description

  get '/:universe/events', to: 'events#index', as: :events_index
  get '/:universe/events/:name', to: 'events#show', as: :event_show, constraints: { name: /[^\/]+/ }
  get '/:universe/events/:event/description', to: 'events#description', as: :event_description, constraints: { event: /[^\/]+/ }
  post '/:universe/events/:event/description', to: 'events#update_description', as: :event_update_description, constraints: { event: /[^\/]+/ }
  post '/:universe/events/:event/locations/add/:location', to: 'events#add_location', as: :event_add_location
  post '/:universe/events/:event/locations/remove/:location', to: 'events#remove_location', as: :event_remove_location 
end

app/controllers/universes_controller.rb
class UniversesController < ApplicationController
  def index
    @universes = Universe.all
  end

  def show
    @universe = Universe.find_by(name: params[:name])
    @events = @universe.events
  end

  def description
    universe = Universe.find_by(name: params[:name])
    @description = ""

    if ! universe.nil?
      @description = universe.description
    end
  end

  def update_description
    @universe = Universe.find_by(name: params[:name])
    if ! @universe.nil?
      @universe.description = params[:description]
      @universe.save
    end
  end
end

app/helpers/universes_helper.rb
module UniversesHelper
end

app/views/universes/index.html.erb
<% content_for :head do %>
  Universe Index
<% end %>

<div class="row">
  <div class="col-xs-12">
    <div class="page-header">
      <h1>Universe Index</h1>
    </div>
  </div>
</div>
<div class="row">
  <% @universes.each do |universe| %>
    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
      <div class="panel panel-default">
        <div class="panel-body">
          <h3><%= link_to universe.name, universe_detail_path(universe.name) %></h3>
          <p><%= universe.description %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/universes/show.html.erb
<% content_for :head do %>
  <%= @universe.name %>
<% end %>

<div class="row">
  <div class="col-xs-12 page-header">
      <h1><%= @universe.name %></h1>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-8">
    <span id="description-text"><%= render_markdown(@universe.description) %></span> <a href="#" data-toggle="modal" data-target="#descriptionModal">edit</a>
  </div>
</div>
<div class="row">
  <div class="col-xs-12 col-sm-4">
    <h3 class="text-center"><%= link_to "Events", events_index_path(@universe.name) %></h3>
    <div class="text-center"><%= pluralize(@universe.events.length, "event") %></div>
    <div class="row">
      <% @universe.events.sort { |a, b| a.updated_at <=> b.updated_at }.each do |event| %>
        <div class="col-xs-8">
          <strong><%= link_to event.name, event_show_path(@universe.name, event.name) %></strong>
        </div>
        <div class="col-xs-4 text-muted text-right">
          <%= event.time_instant.slot_1.to_s + " " + event.time_instant.era.abbreviation %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-xs-12 col-sm-4">
    <h3 class="text-center">People</h3>
    <div class="text-center"><%= pluralize(@universe.people.length, "person") %></div>
    <div class="row">
      <% @universe.people.sort { |a, b| a.updated_at <=> b.updated_at }.each do |person| %>
        <div class="col-xs-8">
          <strong><%= person.name %></strong>
        </div>
        <div class="col-xs-4 text-muted text-right">

        </div>
        <div class="col-xs-12">

        </div>
      <% end %>
    </div>
  </div>
  <div class="col-xs-12 col-sm-4">
    <%= link_to locations_index_path(@universe.name) do %>
      <h3 class="text-center">Locations</h3>
    <% end %>
    <div class="text-center"><%= pluralize(@universe.locations.length, "location") %></div>
    <div class="row">
      <% @universe.locations.sort { |a, b| a.updated_at <=> b.updated_at }.each do |location| %>
        <div class="col-xs-8">
          <strong><%= link_to location.name, location_show_path(@universe.name, location.name) %></strong>
        </div>
        <div class="col-xs-4 text-muted text-right">
          <%= location.part_of.nil? ? "" : location.part_of.name %>
        </div>
        <!--<div class="col-xs-12">
          <p><%= location.description %></p>
        </div>-->
      <% end %>
    </div>
  </div>
</div>


<div id="descriptionModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Edit Description</h4>
      </div>
      <%= form_tag("/#{@universe.name}/description", id: "update-description-form", remote: true) do %>
        <div class="modal-body">
          <div class="form-group">
            <%= text_area_tag(:description, "", class: "form-control", rows: "12") %>
          </div>
        </div>
        <div class="modal-footer">
          <%= submit_tag("Update", class: "btn btn-primary") %>
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  $(function() {
    $("#descriptionModal").on('shown.bs.modal', function () {
      $.ajax({
        url: "/<%= @universe.name %>/description",
        processData: false,
        contentType: false,
        accepts: 'script',
      });

      //$("#description").val($("#description-text").html());
      $("#description").focus();
    });
  });
</script>

app/views/universes/update_description.js.erb
<% if @universe.nil? %>

<% elsif @universe.errors.any? %>

<% else %>
  $("#description-text").html("<%= j render_markdown(@universe.description) %>");
<% end %>