config/routes.rb
Rails.application.routes.draw do
  root 'universes#index'

  get '/:name', to: 'universes#show', as: :universe_detail

  get '/:name/locations', to: 'locations#index', as: :locations_index
  get '/locations/drill/:id', to: 'locations#drill', as: :location_drill
  get '/locations/climb/:id', to: 'locations#drill', as: :location_climb
  get '/:name/locations/:location', to: 'locations#show', as: :location_show
  post '/:name/locations/search', to: 'locations#search', as: :location_search
  get '/:universe/locations/:location/description', to: 'locations#description', as: :location_description
  post '/:universe/locations/:location/description', to: 'locations#update_description', as: :location_update_description
  post '/locations/create', to: 'locations#create', as: :location_create

  get '/:name/people', to: 'people#index', as: :people_index
  get '/:name/description', to: 'universes#description', as: :universe_description
  post '/:name/description', to: 'universes#update_description', as: :universe_update_description

  get '/:universe/events', to: 'events#index', as: :events_index
  get '/:universe/events/:name', to: 'events#show', as: :event_show, constraints: { name: /[^\/]+/ }
  get '/:universe/events/:event/description', to: 'events#description', as: :event_description, constraints: { event: /[^\/]+/ }
  post '/:universe/events/:event/description', to: 'events#update_description', as: :event_update_description, constraints: { event: /[^\/]+/ }
  post '/:universe/events/:event/locations/add/:location', to: 'events#add_location', as: :event_add_location
  post '/:universe/events/:event/locations/remove/:location', to: 'events#remove_location', as: :event_remove_location 
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :universe
  belongs_to :part_of, class_name: 'Location', foreign_key: 'part_of_id'
  has_many :sub_locations, class_name: 'Location', foreign_key: 'part_of_id'
  has_and_belongs_to_many :events, join_table: 'event_locations', uniq: true

  validates :name, presence: true, length: { in: 2..255 }
  validates :universe, presence: true
  validates :description, length: { maximum: 65536 }
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @universe = Universe.find_by(name: params[:name])
    @locations = @universe.locations.where(part_of: nil)
    @new_location = Location.new

    @all_locations = Location.where(universe: @universe)
    @all_locations << Location.new(id: -1, name: "None")
    @all_locations = @all_locations.sort { |a,b| a.id <=> b.id }
  end

  def show
    @universe = Universe.find_by(name: params[:name])
    @location = Location.find_by(name: params[:location], universe: @universe)
  end

  def search
    @locations = Location.where(Location.arel_table[:name].matches("%#{params[:criteria]}%")).uniq
  end

  def create
    @location = Location.new(create_params)

    if @location.part_of == nil
      @location.part_of = nil
    end

    @location.save
    redirect_to location_show_path(@location.universe.name, @location.name), notice: "Location successfully created."
  end

  def drill
    @head = Location.find(params[:id])
    @locations = Location.where(part_of: params[:id])
  end

  def climb
    @locations = Location.find(part_of: params[:id])
  end

  def description
    universe = Universe.find_by(name: params[:universe])
    location = Location.find_by(name: params[:location], universe: universe)
    @description = ""

    if ! location.nil?
      @description = location.description
    end
  end

  def update_description
    universe = Universe.find_by(name: params[:universe])

    if ! universe.nil?
      @location = Location.find_by(name: params[:location], universe: universe)
      @location.description = params[:description]

      @location.save
    end
  end

  private
    def create_params
      params.require(:location).permit(:name, :description, :part_of_id, :universe_id)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_location.html.erb
<div class="row location-result">
  <div class="col-xs-12">
    <h4><%= link_to location.name, location_show_path(location.universe.name, location.name) %></h4>
  </div>
  <div class="col-xs-2 text-right text-muted">
    <div class="row">
      <% if location.part_of != nil %>
        <div class="col-xs-12">
          <span class="text-muted"><i>part of </i></span>
          <%= link_to(location_climb_path(location.part_of), remote: true) do %>
            <%= location.part_of.name %>
          <% end %>
        </div>
      <% end %>
      <div class="col-xs-12">
        <% if location.sub_locations.length > 0 %>
          <%= link_to(location_drill_path(location), remote: true) do %>
            <%= pluralize(location.sub_locations.length, "sublocation") %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-xs-10">
    <%= render_markdown(trim_to_suit(location.description)) %>
  </div>
</div>

app/views/locations/_new_modal.html.erb
<div id="new-location-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Create New Location</h4>
      </div>
      <%= form_for(@new_location, url: location_create_path, method: :post, html: { class: "form" }) do |f| %>
        <div class="modal-body">
          <%= f.hidden_field :universe_id, value: @universe.id %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: "form-control", rows: 6 %>
          </div>
          <div class="form-group">
            <%= f.label :part_of %>
            <%= f.select :part_of_id, @all_locations.collect {|l| [ l.name, l.id] }, {}, class: "form-control" %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/locations/drill.js.erb
$("#location-listing").fadeOut(150, function() {
  $(this).empty();

  <% if @locations.length > 0 %>
    $("#location-listing").append("<%= j render(partial: @locations) %>");
    $("#location-listing").fadeIn(150);
  <% else %>

  <% end %>
});

$("#location-number").fadeOut(150, function() {
  $(this).html("<%= @locations.length %>");
  $(this).fadeIn(150);
});

$("#location-scope-text").fadeOut(150, function() {
  $(this).html("Here are the locations within <%= @head.name %>.");
  $(this).fadeIn(150);
});

app/views/locations/index.html.erb
<% content_for :head do %>
  Locations | <%= @universe.name %>
<% end %>

<div class="row">
  <div class="col-xs-12 page-header">
      <h1><%= @universe.name %> <small>Locations</small></h1>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <div class="well well-sm">
      <div class="row">
        <div class="col-xs-2">
          <%= link_to "Back to Index", universe_detail_path(@universe.name) %>
        </div>
        <div class="col-xs-6">
          <%= form_tag location_search_path(@universe.name), id: 'search-form', class: 'form-inline', remote: true, role: "form" do %>
            <div class="form-group">
                <%= text_field_tag 'criteria', nil, class: 'form-control', placeholder: "Search Locations" %>
            </div>
            <%= submit_tag "Search", class: "btn btn-default" %>
          <% end %>
        </div>
        <div class="col-xs-4">
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#new-location-modal">New Location</button>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    Currently tracking <strong><span id="location-number"><%= @universe.locations.length %></span></strong> locations.
    <span id="location-scope-text">Here are the top level locations.</span>
  </div>
</div>
<div class="row">
  <div id="location-listing" class="col-xs-12">
    <%= render partial: @locations %>
  </div>
</div>

<%= render partial: 'new_modal' %>

<script>
  $(function() {
    $("#criteria").keyup(function() {
      if ($(this).val().length > 1) {
        hide_results();
        $(this).closest("form").submit();
      }
    });
  });

  function hide_results() {
    $("#location-listing .location-result").remove();
  }
</script>

app/views/locations/search.js.erb
<% if @locations.length > 0 %>
  $("#location-listing").append("<%= j render(partial: @locations) %>");
<% else %>
  console.log("no results");
<% end %>

app/views/locations/show.html.erb
<% content_for :head do %>
  <%= @location.name %> | <%= @location.universe.name %>
<% end %>

<div class="row">
  <div class="col-xs-12 page-header">
      <h1><%= @location.name.upcase %></h1>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <div class="well well-sm">
      <%= link_to "Back to Locations Index", locations_index_path(@location.universe.name) %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xs-8">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-6">
            Description
          </div>
          <div class="col-xs-6 text-right">
            <a href="#" data-toggle="modal" data-target="#descriptionModal">edit</a>
          </div>
        </div>
      </div>
      <div id="description-text" class="panel-body">
        <%= render_markdown(@location.description) %>
      </div>
    </div>
  </div>
  <div class="col-xs-4">
    <div class="row">
      <% if @location.part_of.nil? == false %>
        <div class="col-xs-12">
          <div class="panel panel-default">
            <div class="panel-heading">Part Of</div>
            <div class="panel-body">
              <%= link_to @location.part_of.name, location_show_path(@location.universe.name, @location.part_of.name) %>
            </div>
          </div>
        </div>
      <% end %>
      <div class="col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading">Sub Locations</div>
          <div class="panel-body">
            <div class="row">
              <% if @location.sub_locations.length > 0 %>
                <% @location.sub_locations.each do |sub_location| %>
                  <div class="col-xs-12">
                    <%= link_to sub_location.name, location_show_path(@location.universe.name, sub_location.name) %>
                  </div>
                <% end %>
              <% else %>
                <div class="col-xs-12">
                  <div class="alert alert-info">No Sub Locations</div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading">Events</div>
          <div class="panel-body">
            <div class="row">
              <% if @location.events.length > 0 %>
                <% @location.events.each do |event| %>
                  <div class="col-xs-12">
                    <%= link_to event.name, event_show_path(@location.universe.name, event.name) %>
                  </div>
                <% end %>
              <% else %>
                <div class="col-xs-12">
                  <div class="alert alert-info">No Events</div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="descriptionModal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Edit Description</h4>
      </div>
      <%= form_tag("/#{@location.universe.name}/locations/#{@location.name}/description", id: "update-description-form", remote: true) do %>
        <div class="modal-body">
          <div class="form-group">
            <%= text_area_tag(:description, "", class: "form-control", rows: "12") %>
          </div>
        </div>
        <div class="modal-footer">
          <%= submit_tag("Update", class: "btn btn-primary") %>
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  $(function() {
    $("#descriptionModal").on('shown.bs.modal', function () {
      $.ajax({
        url: "/<%= @location.universe.name %>/locations/<%= @location.name %>/description",
        processData: false,
        contentType: false,
        accepts: 'script',
      });

      $("#description").focus();
    });
  });
</script>

app/views/locations/update_description.js.erb
<% if @location.nil? %>

<% elsif @location.errors.any? %>

<% else %>
  $("#description-text").html("<%= j render_markdown(@location.description) %>");
<% end %>