config/routes.rb
Rails.application.routes.draw do
  root 'universes#index'

  get '/:name', to: 'universes#show', as: :universe_detail

  get '/:name/locations', to: 'locations#index', as: :locations_index
  get '/locations/drill/:id', to: 'locations#drill', as: :location_drill
  get '/locations/climb/:id', to: 'locations#drill', as: :location_climb
  get '/:name/locations/:location', to: 'locations#show', as: :location_show
  post '/:name/locations/search', to: 'locations#search', as: :location_search
  get '/:universe/locations/:location/description', to: 'locations#description', as: :location_description
  post '/:universe/locations/:location/description', to: 'locations#update_description', as: :location_update_description
  post '/locations/create', to: 'locations#create', as: :location_create

  get '/:name/people', to: 'people#index', as: :people_index
  get '/:name/description', to: 'universes#description', as: :universe_description
  post '/:name/description', to: 'universes#update_description', as: :universe_update_description

  get '/:universe/events', to: 'events#index', as: :events_index
  get '/:universe/events/:name', to: 'events#show', as: :event_show, constraints: { name: /[^\/]+/ }
  get '/:universe/events/:event/description', to: 'events#description', as: :event_description, constraints: { event: /[^\/]+/ }
  post '/:universe/events/:event/description', to: 'events#update_description', as: :event_update_description, constraints: { event: /[^\/]+/ }
  post '/:universe/events/:event/locations/add/:location', to: 'events#add_location', as: :event_add_location
  post '/:universe/events/:event/locations/remove/:location', to: 'events#remove_location', as: :event_remove_location 
end

app/views/layouts/_footer.html.erb
<div class="footer">
  Timecat
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Timecat</a>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <% if (universe = discover_universe()) != nil %>
          <li><%= link_to universe.name, universe_detail_path(universe.name) %></li>
          <li><%= link_to "People", people_index_path(universe.name) %></li>
          <li><%= link_to "Locations", locations_index_path(universe.name) %></li>
          <li><%= link_to "Events", events_index_path(universe.name) %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right"></ul>
    </div>
  </div>
</nav>

app/views/layouts/_notices.html.erb
<div class="row">
  <div class="col-xs-12">
    <div id="notice-bar" class="alert collapse" role="alert"></div>
  </div>
</div>

<script>
  function notify(alert, msg) {
    $("#notice-bar").slideUp(75, function() {
      $(this).html(msg);
      $(this).removeClass(function(index, css) {
          return (css.match(/(^|\s)alert-\S+/g) || []).join(' ');
      });
      $(this).addClass("alert-" + alert);

      $(this).slideDown(75);
    });
  }

  function hideNotifyBar() {
    $("#notice-bar").slideUp(75);
  }

  function showNotifyBar() {
    $("#notice-bar").slideDown(75);
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :head %> - TimeCat</title>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cabin:700' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/navbar" %>

<div class="container">
  <%= yield %>
</div>

<%= render "layouts/footer" %>
</body>
</html>